### ISSUE TITLE
The guild emblem is optional

### ISSUE THREAD

**Issue by Sejsel** [Archomeda/Gw2Sharp#10]
There are quite a few guilds that have no emblem in the API, for example: https://api.guildwars2.com/v2/guild/bd558153-0f8e-e911-81a8-cde2ac1eed30

```json
{
  "id": "BD558153-0F8E-E911-81A8-CDE2AC1EED30",
  "name": "Aomi",
  "tag": "Aomi"
}
```

The Emblem value is defaulted to an emblem with values of 0, but more importantly the Flags do not work correctly. An `InvalidCastException` is thrown when getting `Gw2Sharp.WebApi.V2.Models.ApiFlags.List` in this case.

To reproduce:
```cs
static async Task Main(string[] args)
{
	var client = new Gw2Client();
	var guild = await client.WebApi.V2.Guild["bd558153-0f8e-e911-81a8-cde2ac1eed30"].GetAsync();
	Console.WriteLine(guild.Emblem.Flags.List);
}
```

Exception:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[Gw2Sharp.WebApi.V2.Models.ApiEnum]' to type 'System.Collections.Generic.IReadOnlyList`1[Gw2Sharp.WebApi.V2.Models.ApiEnum`1[Gw2Sharp.WebApi.V2.Models.GuildEmblemFlag]]'.
   at Gw2Sharp.WebApi.V2.Models.ApiFlags`1.get_List()
   at Gw2SharpTest.Program.Main(String[] args) in /tmp/Gw2SharpTest/Gw2SharpTest/Program.cs:line 13
   at Gw2SharpTest.Program.<Main>(String[] args)
```

**Comment by Archomeda** [comment]
Ah. I never thought that a guild wouldn't have the guild emblem set. I'll make that nullable.

Regarding the ApiFlags. It would seem that it's a side effect when constructing the default. I'll see if I can get rid of the base non-generic ApiFlags and ApiEnum, as these seem to be causing the issue.
