### ISSUE TITLE
Keep duplicates in a ManyAsync result?

### ISSUE THREAD

**Issue by agaertner** [Archomeda/Gw2Sharp#112]
The background and foreground colors of a guild emblem rely on index order in which they are applied on the guild emblem layers.
When I combine them into one list (keeping the order) for a single ManyAsync request ManyAsync will remove duplicates from the result.
Could this behaviour be changed so that ManyAsync will just keep duplicates in the result (add as many of one request result as was in the request parameter in order)? In the meantime I will have to make separate requests.

**Comment by Archomeda** [comment]
While Gw2Sharp does filter out duplicates in the request, the API itself also filters the duplicates in the results, even if you were to request multiple of the same id (see https://api.guildwars2.com/v2/colors?ids=1,2,3,4,4,3,2,1)

I'm not going to add any redundant logic to support this. You can easily apply your own logic to get all the colors that you want, and get the correct ones out of the list.

**Comment by agaertner** [comment]
As I said I already did. Good to know though. :)
