### ISSUE TITLE
You could add a field to get the time of day in Tyria

### ISSUE THREAD

**Issue by TybaIt** [Archomeda/Gw2Sharp#74]
https://wiki.guildwars2.com/wiki/Day_and_night

I know it doesn't wrap anything from the API or Api/MumbleLink but you could just provide one for the global time (excluding the zones not in the cycle).

**Comment by Archomeda** [comment]
Hardcoding stuff like the day/night cycle is currently out of scope for this project (e.g. event timers also fall under that). Gw2Sharp is a wrapper for GW2's API (whether it being the web API, or Mumble Link, etc.). As long as the API doesn't expose this as an endpoint, it won't be an addition in Gw2Sharp.
That said, adding this cycle into your own project should be simple enough though.
